### ISSUE TITLE
The probe mount in the V2 version is very loose compared to the original one found in the /stl folder.

### ISSUE THREAD

**Issue by Ch4rlesB** [Annex-Engineering/Quickdraw_Probe#3]
After printing both with the same settings, the V2 fixed bed (Probe_dock_mount_x1_Rev1.STL) version of the probe mount has ALOT of play.
I printed out the original one in the /stl folder (microswitch_probe_dock_x1_rev5.STL) and this one has little to no play but is not dimensioned for the V2 as its too long and beefy.

Would it be possible to modify the V2 version to have a secure fit as the amount of play seems more than tolerable.

This is the V2 Fixed bed (Probe_dock_mount_x1_Rev1.STL)
https://user-images.githubusercontent.com/38528657/122409997-92600900-cf51-11eb-8131-289b953f17c4.mp4

**Comment by Annex-Engineering** [comment]
please see the updated STLs on the repo. sorry for the delay
