### ISSUE TITLE
"Magprobe" link in the readme is broken

### ISSUE THREAD

**Issue by patbohn** [Annex-Engineering/Quickdraw_Probe#7]
Hi, 

The link for the "magprobe" in the readme.md currently goes to a 404: https://github.com/Annex-Engineering/Quickdraw_Probe/blob/main/STLs/omron_d2f-5_microswitch_probe_body_x1_rev2.STL

Thank you for developing and sharing this awesome design, cheers!

**Comment by PapeJelly** [comment]
Hi Patbohn, as of today this should be repaired. Thanks for you message!
