### ISSUE TITLE
Could the readme contain information about magnet diameter and height? 

### ISSUE THREAD

**Issue by patbohn** [Annex-Engineering/Quickdraw_Probe#8]
Hi, 
I'd like to build my own Quickraw Probe. However, I couldn't find the information about the magnet size (diameter and height) on the page; is it not there or do I need another coffee? 
Cheers

**Comment by hejiawencc** [comment]
And I also hope to provide more information, such as the number of magnets.

**Comment by hejiawencc** [comment]
BOM has been provided. README on different machines

**Comment by PapeJelly** [comment]
For future reference i added a link to the sourcing sheet Annex has for all their stuff
